"""The storage layer, against real Postgres and Redis.

The claim that matters here is **idempotency under redelivery**. At-least-once
delivery means a replayed report will arrive; the unique constraint plus
`ON CONFLICT DO NOTHING` is what stops that inflating history. A mock cannot
demonstrate that, because the constraint lives in the database.

The schema is applied by Alembic, not by `metadata.create_all`, so these tests
run against the schema that actually ships.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from acp.common.contracts import Alert as AlertModel
from acp.common.contracts import (
    AlertKind,
    AlertState,
    ConflictEvidence,
    DataSource,
    Severity,
)
from acp.storage.stores import LiveAlertStore, LiveTrackStore, TrackHistoryStore
from tests.integration.helpers import a_track_update, seconds_apart, until

pytestmark = pytest.mark.integration


def an_alert(key: str = "predicted_conflict:trk-a:trk-b", **overrides: object) -> AlertModel:
    now = datetime.now(UTC)
    fields: dict[str, object] = {
        "alert_id": "al-1",
        "alert_key": key,
        "kind": AlertKind.PREDICTED_CONFLICT,
        "severity": Severity.CAUTION,
        "state": AlertState.NEW,
        "raised_at": now,
        "updated_at": now,
        "track_ids": ("trk-a", "trk-b"),
        "reason_codes": ("horizontal_below_standard",),
        "summary": "integration alert",
        "conflict": ConflictEvidence(
            time_to_cpa_s=120.0,
            min_horizontal_sep_nm=2.0,
            min_vertical_sep_ft=400.0,
            lookahead_s=300.0,
            horizontal_standard_nm=5.0,
            vertical_standard_ft=1000.0,
        ),
        "source": DataSource.SIMULATOR,
    }
    fields.update(overrides)
    return AlertModel(**fields)  # type: ignore[arg-type]


# --------------------------------------------------------------------------
# Postgres
# --------------------------------------------------------------------------


async def test_the_migration_produces_the_tables_the_writer_expects(
    migrated_postgres: str,
) -> None:
    engine = create_async_engine(migrated_postgres)
    try:
        async with engine.connect() as conn:
            tables = {
                row[0]
                for row in (
                    await conn.execute(
                        text("select tablename from pg_tables where schemaname='public'")
                    )
                ).all()
            }
            constraints = {
                row[0]
                for row in (
                    await conn.execute(
                        text(
                            "select conname from pg_constraint"
                            " where conrelid='track_points'::regclass"
                        )
                    )
                ).all()
            }
    finally:
        await engine.dispose()

    assert {"tracks", "track_points"} <= tables
    # Referenced by name in the writer's ON CONFLICT clause. An autogenerated
    # rename would break idempotency silently, so the name is pinned.
    assert "uq_track_points_track_observed" in constraints


async def test_track_history_is_written_and_read_back(migrated_postgres: str) -> None:
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    try:
        moments = seconds_apart(5, start=datetime(2026, 3, 1, tzinfo=UTC))
        await store.record([a_track_update(track_id="trk-read", at=m) for m in moments])

        history = await store.history("trk-read")
        assert len(history) == 5
        # Oldest first: a display drawing a trail needs them in flight order.
        assert [row["observed_at"] for row in history] == moments
    finally:
        await store.dispose()


async def test_replaying_the_same_batch_does_not_duplicate_history(
    migrated_postgres: str,
) -> None:
    """The idempotency claim, demonstrated against the real constraint.

    Without it, every consumer restart would silently inflate track history in a
    way that is very hard to notice afterwards.
    """
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    try:
        moments = seconds_apart(20, start=datetime(2026, 3, 2, tzinfo=UTC))
        batch = [a_track_update(track_id="trk-replay", at=m) for m in moments]

        await store.record(batch)
        await store.record(batch)
        await store.record(batch)

        assert len(await store.history("trk-replay")) == 20
    finally:
        await store.dispose()


async def test_a_batch_holding_many_updates_for_one_track_is_accepted(
    migrated_postgres: str,
) -> None:
    """Postgres refuses an ON CONFLICT DO UPDATE that touches a row twice.

    A batch normally holds several updates per aircraft, so the writer collapses
    to the newest per track. This is the regression test for the crash that
    found it.
    """
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    try:
        moments = seconds_apart(50, start=datetime(2026, 3, 3, tzinfo=UTC))
        await store.record([a_track_update(track_id="trk-batch", at=m) for m in moments])
        assert len(await store.history("trk-batch")) == 50
    finally:
        await store.dispose()


async def test_the_track_row_reflects_the_newest_update(migrated_postgres: str) -> None:
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    engine = create_async_engine(migrated_postgres)
    try:
        moments = seconds_apart(10, start=datetime(2026, 3, 4, tzinfo=UTC))
        await store.record([a_track_update(track_id="trk-latest", at=m) for m in moments])

        async with engine.connect() as conn:
            row = (
                await conn.execute(
                    text(
                        "select first_seen_at, last_seen_at from tracks where track_id='trk-latest'"
                    )
                )
            ).one()
        # first_seen_at must stay at the first, not follow the last.
        assert row[0] == moments[0]
        assert row[1] == moments[-1]
    finally:
        await store.dispose()
        await engine.dispose()


async def test_history_for_an_unknown_track_is_empty_not_an_error(
    migrated_postgres: str,
) -> None:
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    try:
        assert await store.history("trk-does-not-exist") == []
    finally:
        await store.dispose()


async def test_readiness_reports_a_reachable_database(migrated_postgres: str) -> None:
    store = TrackHistoryStore.from_dsn(migrated_postgres)
    try:
        assert await store.ping() is True
    finally:
        await store.dispose()


async def test_readiness_reports_an_unreachable_database_without_raising() -> None:
    """A readiness probe that raises turns a dependency blip into a 500."""
    store = TrackHistoryStore.from_dsn("postgresql+asyncpg://acp:acp@127.0.0.1:1/none")
    try:
        assert await store.ping() is False
    finally:
        await store.dispose()


# --------------------------------------------------------------------------
# Redis
# --------------------------------------------------------------------------


async def test_the_live_picture_holds_the_newest_update_per_track(clean_redis: str) -> None:
    store = LiveTrackStore.from_url(clean_redis)
    try:
        moments = seconds_apart(5)
        for index, moment in enumerate(moments):
            await store.publish([a_track_update(at=moment, lon=-75.0 + index)])

        live = await store.live()
        assert len(live) == 1
        assert live[0].lon == pytest.approx(-75.0 + 4)
    finally:
        await store.close()


async def test_a_stale_track_falls_outside_the_window(clean_redis: str) -> None:
    store = LiveTrackStore.from_url(clean_redis)
    try:
        old = datetime.now(UTC) - timedelta(minutes=5)
        await store.publish([a_track_update(at=old)])
        assert await store.live(since=datetime.now(UTC) - timedelta(seconds=20)) == []
        assert len(await store.live()) == 1
    finally:
        await store.close()


async def test_a_forgotten_track_disappears_immediately(clean_redis: str) -> None:
    """A terminated aircraft must leave the display rather than wait for a TTL."""
    store = LiveTrackStore.from_url(clean_redis)
    try:
        await store.publish([a_track_update()])
        await store.forget(["trk-a1b2c3"])
        assert await store.live() == []
    finally:
        await store.close()


async def test_the_live_entry_expires_on_its_own(clean_redis: str) -> None:
    """If the tracker dies the picture must empty itself.

    A frozen display is more dangerous than an empty one, so expiry is a safety
    property rather than a caching detail.
    """
    store = LiveTrackStore.from_url(clean_redis, ttl_s=1)
    try:
        await store.publish([a_track_update()])
        assert len(await store.live()) == 1

        async def gone() -> bool:
            return not await store.live()

        await until(gone, timeout_s=15.0, description="the live entry to expire")
    finally:
        await store.close()


async def test_active_alerts_round_trip(clean_redis: str) -> None:
    store = LiveAlertStore.from_url(clean_redis)
    try:
        await store.apply([an_alert()])
        active = await store.active()
        assert len(active) == 1
        assert active[0].conflict is not None
        assert active[0].conflict.min_horizontal_sep_nm == 2.0
    finally:
        await store.close()


async def test_a_cleared_alert_is_deleted_rather_than_flagged(clean_redis: str) -> None:
    """The endpoint's contract is "what is wrong now".

    Keeping cleared alerts with a flag would mean every consumer had to remember
    to filter them, and the first one that forgot would show a resolved conflict
    as live.
    """
    store = LiveAlertStore.from_url(clean_redis)
    try:
        await store.apply([an_alert()])
        await store.apply([an_alert(state=AlertState.CLEARED)])
        assert await store.active() == []
    finally:
        await store.close()


async def test_a_sustained_alert_replaces_the_previous_state(clean_redis: str) -> None:
    store = LiveAlertStore.from_url(clean_redis)
    try:
        await store.apply([an_alert(summary="first")])
        await store.apply([an_alert(state=AlertState.SUSTAINED, summary="second")])
        active = await store.active()
        assert len(active) == 1
        assert active[0].summary == "second"
        assert active[0].state is AlertState.SUSTAINED
    finally:
        await store.close()


async def test_alerts_expire_if_nothing_maintains_them(clean_redis: str) -> None:
    """If the conformance service dies, its alerts must not sit on the display
    forever with nothing keeping them current."""
    store = LiveAlertStore.from_url(clean_redis, ttl_s=1)
    try:
        await store.apply([an_alert()])
        assert len(await store.active()) == 1

        async def gone() -> bool:
            return not await store.active()

        await until(gone, timeout_s=15.0, description="the alert to expire")
    finally:
        await store.close()


async def test_redis_readiness_reports_an_unreachable_server_without_raising() -> None:
    store = LiveTrackStore.from_url("redis://127.0.0.1:1/0")
    try:
        assert await store.ping() is False
    finally:
        await store.close()


async def test_tracks_and_alerts_do_not_collide_in_one_redis(clean_redis: str) -> None:
    """Both stores share a database; their key prefixes must not overlap."""
    tracks = LiveTrackStore.from_url(clean_redis)
    alerts = LiveAlertStore.from_url(clean_redis)
    try:
        await tracks.publish([a_track_update()])
        await alerts.apply([an_alert()])
        assert len(await tracks.live()) == 1
        assert len(await alerts.active()) == 1
    finally:
        await tracks.close()
        await alerts.close()
