"""Initial track storage: tracks and track_points.

Written by hand rather than autogenerated so the constraint names and the
downgrade path are deliberate. An autogenerated migration is fine for a toy and
a liability the first time one has to be reviewed or reversed.

Revision ID: 0001
Revises:
Created: 2026-08-15
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tracks",
        sa.Column("track_id", sa.String(64), primary_key=True),
        sa.Column("icao24", sa.String(6), nullable=False),
        sa.Column("callsign", sa.String(16)),
        sa.Column("scenario_id", sa.String(64)),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(16), nullable=False),
        sa.Column("update_count", sa.Integer, nullable=False),
    )
    op.create_index("ix_tracks_icao24", "tracks", ["icao24"])
    op.create_index("ix_tracks_scenario_id", "tracks", ["scenario_id"])

    op.create_table(
        "track_points",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("track_id", sa.String(64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        sa.Column("altitude_ft", sa.Float, nullable=False),
        sa.Column("ground_speed_kt", sa.Float, nullable=False),
        sa.Column("track_deg", sa.Float, nullable=False),
        sa.Column("vertical_rate_fpm", sa.Float, nullable=False),
        sa.Column("turn_rate_deg_s", sa.Float, nullable=False),
        sa.Column("position_uncertainty_m", sa.Float, nullable=False),
        # Named explicitly because the writer references this constraint by name
        # in its ON CONFLICT clause. An auto-generated name would work until
        # someone regenerated it differently and idempotency broke silently.
        sa.UniqueConstraint("track_id", "observed_at", name="uq_track_points_track_observed"),
    )
    op.create_index("ix_track_points_track_time", "track_points", ["track_id", "observed_at"])


def downgrade() -> None:
    op.drop_index("ix_track_points_track_time", table_name="track_points")
    op.drop_table("track_points")
    op.drop_index("ix_tracks_scenario_id", table_name="tracks")
    op.drop_index("ix_tracks_icao24", table_name="tracks")
    op.drop_table("tracks")
